#!/usr/bin/env bash

# Print commands and their arguments as they are executed.
#set -x

get_password ()
{
	echo $(head -n 4096 /dev/urandom | tr -cd '[:alnum:]' | head -c ${1})
}

OPTS_SSH_USER="${SSH_USER:-app-admin}"
OPTS_SSH_USER_PASSWORD="${SSH_USER_PASSWORD:-$(get_password 8)}"

# Initialise
echo "Initialise SSH..."

# Generate new host keys
ssh-keygen -q -N "" -t rsa -f /etc/ssh/ssh_host_rsa_key
ssh-keygen -q -N "" -t dsa -f /etc/ssh/ssh_host_dsa_key

useradd -u 500 -m -G users ${OPTS_SSH_USER}

# Set user password
echo "${OPTS_SSH_USER}:${OPTS_SSH_USER_PASSWORD}" | chpasswd

echo
echo "--------------------------------------------------------------------------------"
echo "SSH Credentials: "
echo "${OPTS_SSH_USER} : ${OPTS_SSH_USER_PASSWORD}"
#echo
#echo "RSA Host Key: "
#echo "$(cat /etc/ssh/ssh_host_rsa_key)"
#echo
#echo "DSA Host Key: "
#echo "$(cat /etc/ssh/ssh_host_dsa_key)"
echo "--------------------------------------------------------------------------------"
echo

# Allow some time for supervisor_stdout to start
sleep 2

exit 0
